# Following testing rule works
# - alias: 'Random sensor trigger twitter'
#   trigger:
#     platform: state
#     entity_id: binary_sensor.random_change
#     to: "on"
#   action:
#     service: notify.twitter_wang3an
#     data:
#       message:
#     data_template:
#       message: >
#         Auto tweet : Random value {{ states.sensor.random_1.state }} is less than 50.  

- alias: 'Daily modem power off at 5:50'
  trigger:
    platform: time
    at: '05:50:00'
  action:
    service: switch.turn_off
    entity_id: switch.modem_xiaomi_mi_wifi_socket_basic
- alias: 'Daily modem power on at 5:53'
  trigger:
    platform: time
    at: '05:53:00'
  action:
    service: switch.turn_on
    entity_id: switch.modem_xiaomi_mi_wifi_socket_basic

# - alias: 'Daily orvibo power on at 6:00'
#   trigger:
#     platform: time
#     at: '06:00:00'
#   action:
#     service: switch.turn_on
#     entity_id: switch.orange_orvibo_wifi_socket
# - alias: 'Daily orvibo power off at 7:00'
#   trigger:
#     platform: time
#     at: '07:00:00'
#   action:
#     service: switch.turn_off
#     entity_id: switch.orange_orvibo_wifi_socket

- alias: 'TTS on finished cleaning'
  trigger:
    platform: state
    entity_id: vacuum.cleaner_xiaomi_clean_robot
    from: 'on'
    to: 'off'
  action:
    service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: !include tts-cleaner-robot-job-done.yaml
      # message: "My lord, your cleaner robot had just finished cleaning."

- alias: 'TV power on when Chromecast playing'
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'off'
      to: 'idle'
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'off'
      to: 'playing'
  condition:
    condition: state
    entity_id: binary_sensor.skyworth_tv
    state: 'off' # not detected
  action:
    - service: media_player.media_pause # waiting for tv power on
      entity_id: media_player.living_room_tv
    - service: switch.turn_on
      entity_id: switch.skyworth_tv_power
    - delay: '00:00:30' # left some seconds for tv power on
    - service: media_player.media_play # continue playing
      entity_id: media_player.living_room_tv
    - service: device_tracker.see # update TV state
      data:
        dev_id: skyworthtvlan