# Following testing rule works
# - alias: 'Random sensor trigger twitter'
#   trigger:
#     platform: state
#     entity_id: binary_sensor.random_change
#     to: "on"
#   action:
#     service: notify.twitter_wang3an
#     data:
#       message:
#     data_template:
#       message: >
#         Auto tweet : Random value {{ states.sensor.random_1.state }} is less than 50.  

- alias: 'Daily modem power off at 5:50'
  trigger:
    platform: time
    at: '05:50:00'
  action:
    service: switch.turn_off
    entity_id: switch.modem_xiaomi_mi_wifi_socket_basic
- alias: 'Daily modem power on at 5:53'
  trigger:
    platform: time
    at: '05:53:00'
  action:
    service: switch.turn_on
    entity_id: switch.modem_xiaomi_mi_wifi_socket_basic

- alias: 'Daily orvibo power on at 6:00'
  trigger:
    platform: time
    at: '06:00:30'
  action:
    service: switch.turn_on
    entity_id: switch.orange_orvibo_wifi_socket
- alias: 'Daily orvibo power off at 7:00'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.orange_orvibo_wifi_socket

- alias: 'TTS on finished Cleaning'
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_clean_robot
    from: 'on'
    to: 'off'
  action:
    service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: !include cleaner-robot-job-done.yaml
