# Following testing rule works
# - alias: 'Random sensor trigger twitter'
#   trigger:
#     platform: state
#     entity_id: binary_sensor.random_change
#     to: "on"
#   action:
#     service: notify.twitter_wang3an
#     data:
#       message:
#     data_template:
#       message: >
#         Auto tweet : Random value {{ states.sensor.random_1.state }} is less than 50.  

- alias: 'Daily modem power off at 5:50'
  trigger:
    platform: time
    at: '05:50:00'
  action:
    service: switch.turn_off
    entity_id: switch.modem_xiaomi_mi_wifi_socket_basic
- alias: 'Daily modem power on at 5:53'
  trigger:
    platform: time
    at: '05:53:00'
  action:
    service: switch.turn_on
    entity_id: switch.modem_xiaomi_mi_wifi_socket_basic

# - alias: 'Daily orvibo power on at 6:00'
#   trigger:
#     platform: time
#     at: '06:00:00'
#   action:
#     service: switch.turn_on
#     entity_id: switch.orange_orvibo_wifi_socket
# - alias: 'Daily orvibo power off at 7:00'
#   trigger:
#     platform: time
#     at: '07:00:00'
#   action:
#     service: switch.turn_off
#     entity_id: switch.orange_orvibo_wifi_socket

- alias: 'TTS on finished cleaning'
  trigger:
    platform: state
    entity_id: vacuum.cleaner_xiaomi_cleaner_robot
    from: 'on'
    to: 'off'
  action:
    service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      # message: !include tts-cleaner-robot-job-done.yaml # this mode won't work
      message: "My lord, your cleaner robot had just finished cleaning."

- alias: 'TV power on when Chromecast playing'
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'off'
      to: 'idle'
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'off'
      to: 'playing'
  condition:
    condition: state
    entity_id: binary_sensor.skyworth_tv
    state: 'off' # not detected
  action:
    - service: media_player.media_pause # waiting for tv power on
      entity_id: media_player.living_room_tv
    - service: switch.turn_on
      entity_id: switch.skyworth_tv_power
    - delay: '00:00:30' # left some seconds for tv power on
    - service: media_player.media_play # continue playing
      entity_id: media_player.living_room_tv

################################################################
# begin : automation for "stop working, take a walk"
# - alias: "TTS on work event: start" # by setting local timer
#   trigger:
#     - platform: state
#       entity_id: input_boolean.work_state
#       to: 'on'
#   action:
#     - service: tts.google_say
#       entity_id: media_player.living_room_home
#       data:
#         message: "Start to work, timer set."
#     - service: timer.start # start the timer for x minutes
#       entity_id: timer.timer_for_tts_start_work
# - alias: "TTS on work event: start"
#   trigger:
#     - platform: homeassistant # handle hass started event
#       event: start
#     - platform: state
#       entity_id: calendar.start_work # handle common runtime event
#       to: 'on' # received an event
#   condition:
#     condition: state
#     entity_id: calendar.start_work
#     state: 'on' # event work is on
#   action:
#     - service: tts.google_say
#       entity_id: media_player.living_room_home
#       data:
#         message: "Start to work, timer set."
#     - service: timer.start # start the timer for x minutes
#       entity_id: timer.timer_for_tts_start_work

# - alias: "TTS on work event: end"
#   trigger:
#     platform: state
#     entity_id: timer.timer_for_tts_start_work
#     to: 'idle' # work time up
#   action:
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.work_state
#     - service: tts.google_say
#       entity_id: media_player.living_room_home
#       data:
#         message: "Time to take a walk, human!"
#     - service: switch.turn_on # set the signal on
#       entity_id: switch.orange_orvibo_wifi_socket
#     - service: timer.start # start the timer for repeat
#       entity_id: timer.timer_for_tts_repeat_take_a_walk

- alias: "TTS on work event: ended" # by google event
  trigger:
    platform: state
    entity_id: calendar.start_work
    to: 'off' # work event ended
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Time to take a walk, human!"
    - service: switch.turn_on # set the signal on
      entity_id: switch.orange_orvibo_wifi_socket
    - service: timer.start # start the timer for repeat
      entity_id: timer.timer_for_tts_repeat_take_a_walk

- alias: "TTS on work event: repeat after ended"
  trigger:
    platform: state
    entity_id: timer.timer_for_tts_repeat_take_a_walk
    to: 'idle' # time up
  condition:
    condition: state
    entity_id: switch.orange_orvibo_wifi_socket
    state: 'on' # repeat if signal is on
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        # message: "Time to take a walk, human!"
        message: "喂！够了够了，必须站起来走走了！"
        language: "zh"
    - service: timer.start # start this timer again
      entity_id: timer.timer_for_tts_repeat_take_a_walk
# end : automation for "stop working, take a walk"
################################################################

- alias: "TTS on Magic Cube free fall: time"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a704
      action_type: free_fall
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data_template:
        message: >
          Time now: {{ states("sensor.time")}}.
    - service: timer.start # a 10 seconds timer, as a signal for next action: rotate
      entity_id: timer.timer_on_magic_tube_rotated

- alias: "TTS on Magic Cube rotate: volume"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a704
      action_type: rotate
  condition:
    condition: state
    entity_id: timer.timer_on_magic_tube_rotated
    state: 'active' # repeat if signal is on
  action:
    - service_template: >
        {% if trigger.event.data.action_value > 0 %}
            media_player.volume_up
        {% else %}
            media_player.volume_down
        {% endif %}
      entity_id: media_player.living_room_home
    - service: timer.cancel # restart timer
      entity_id: timer.timer_on_magic_tube_rotated
    - service: timer.start
      entity_id: timer.timer_on_magic_tube_rotated

################################################################
# test begin
# - alias: "test on ON"
#   trigger:
#     - platform: state
#       entity_id: input_boolean.test
#       to: 'on'
#   action:
#     - service: xiaomi_aqara.play_ringtone
#       data:
#         gw_mac: !secret xiaomi_gateway_mac
#         ringtone_id: 8
#         ringtone_vol: 8

# - alias: "test on OFF"
#   trigger:
#     - platform: state
#       entity_id: input_boolean.test
#       to: 'off'
#   action:
#     - service: xiaomi_aqara.stop_ringtone
#       data:
#         gw_mac: !secret xiaomi_gateway_mac

- alias: "test on sensor turn bool on"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001db5021
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.test
    state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.test
    # - service: xiaomi_aqara.play_ringtone
    #   data:
    #     gw_mac: !secret xiaomi_gateway_mac
    #     ringtone_id: 8
    #     ringtone_vol: 3

- alias: "test on sensor turn bool off"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001db5021
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.test
    state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.test
    # - service: xiaomi_aqara.stop_ringtone
    #   data:
    #     gw_mac: !secret xiaomi_gateway_mac
# test end
################################################################

 