# - platform: template  # <---------- a kind of platform
#   sensors:            #<----------- this ki1nd "template binary sensor" of sensors
#     random_change:       #<----------- a particular sensor
#       friendly_name: "A random value less than 50"
#       value_template: "{{ states.sensor.random_1.state | float < 50 }}"

# - platform: ping
#   host: 192.168.1.206

- platform: command_line
  name: "skyworth tv"
  command: ping -W 1 -c 1 192.168.1.206 > /dev/null 2>&1 && echo success || echo fail
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 5