- platform: xiaomi_miio
  name: Living room light (Xiaomi Philips Ball)
  host: !secret xiaomi_philips_light_living_room_ip
  token: !secret xiaomi_philips_light_living_room_token

- platform: xiaomi_miio
  name: Small bedroom light (Xiaomi Philips Ball)
  host: !secret xiaomi_philips_light_small_bedroom_ip
  token: !secret xiaomi_philips_light_small_bedroom_token