- platform: xiaomi_miio
  name: Livingroom light (Xiaomi Philips Ball)
  host: !secret xiaomi_philips_light_livingroom_ip
  token: !secret xiaomi_philips_light_livingroom_token

- platform: xiaomi_miio
  name: Small bedroom light (Xiaomi Philips Ball)
  host: !secret xiaomi_philips_light_small_bedroom_ip
  token: !secret xiaomi_philips_light_small_bedroom_token