# - platform: yr
- platform: time_date
  display_options:
    - 'date'
    - 'time'
# - platform: random
#   name: random 1
#   minimum: 0
#   maximum: 100

# World Air Quality Index
- platform: waqi
  token: !secret aqicn_api_token
  locations:
    - zhuhai
    # - macau
  stations:
    - zhuhai
    # - "Subestação Macau Norte"
    # - subestacao-macau-norte

