# - platform: yr
- platform: time_date
  display_options:
    - 'date'
    - 'time'
# - platform: random
#   name: random 1
#   minimum: 0
#   maximum: 100

# World Air Quality Index
- platform: waqi
  token: !secret aqicn_api_token
  locations:
    - zhuhai
    # - macau
  stations:
    - zhuhai
    # - "Subestação Macau Norte"
    # - subestacao-macau-norte

- platform: airvisual
  api_key: !secret airvisual_api_token
  monitored_conditions:
    - us
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  radius: 30000
  show_on_map: false

