- platform: orvibo
  discovery: false
  switches:
    - host: !secret orvibo_wifi_socket_ip
      mac:  !secret orvibo_wifi_socket_mac
      name: "Orange (Orvibo WiFi Socket)"
  # emulated_hue_name: "orange" # no need 

- platform: xiaomi_miio
  name: "Modem (Xiaomi Mi WiFi Socket Basic)"
  host: !secret xiaomi_wifi_socket_basic_ip
  token: !secret xiaomi_wifi_socket_basic_token
  # emulated_hue_name: "modem"  # no need 

- platform: broadlink
  host: !secret broadlink_rm2_switch_ip
  mac: !secret broadlink_rm2_switch_mac
  friendly_name: "Broadlink rm2"
  switches:
    skyworth_tv:
      friendly_name: "TV"
      command_on: !secret broadlink_rm2_switch_skywort_tv_on_packet
      command_off: !secret broadlink_rm2_switch_skywort_tv_on_packet
  # emulated_hue_name: "Skyworth"  # no need 