- platform: orvibo
  discovery: false
  switches:
    - host: !secret orvibo_wifi_socket_s20_ip
      mac:  !secret orvibo_wifi_socket_s20_mac
      name: "Switch Orange"
  # emulated_hue_name: "orange" # no need 

# - platform: orvibo
#   discovery: false
#   switches:
#     - host: !secret orvibo_wifi_socket_s20c_ip hass doesn't support s20c
#       mac:  !secret orvibo_wifi_socket_s20c_mac
#       name: "Switch Orange2"

#- platform: xiaomi_miio
#  name: "mi 1"
#  host: !secret xiaomi_wifi_socket_basic_ip
#  token: !secret xiaomi_wifi_socket_basic_token
#  # emulated_hue_name: "modem"  # no need 

#- platform: xiaomi_miio
#  name: "mi 2"
#  host: !secret xiaomi_wifi_socket_basic_ip_2
#  token: !secret xiaomi_wifi_socket_basic_token_2

- platform: broadlink
  host: !secret broadlink_rm2_switch_ip
  mac: !secret broadlink_rm2_switch_mac
  friendly_name: "Broadlink rm2"
  switches:
    skyworth_tv:
      friendly_name: "TV"
      command_on: !secret remote_control_code_skyworth_tv_on_packet
      command_off: !secret remote_control_code_skyworth_tv_on_packet
    china_mobile_tv_box:
      friendly_name: "TV Box"
      command_on: !secret remote_control_code_china_mobile_tv_box_on_packet
      command_off: !secret remote_control_code_china_mobile_tv_box_on_packet
    air_conditioner:
      friendly_name: "Air Conditioner"
      command_on: !secret remote_control_code_ac_on
      command_off: !secret remote_control_code_ac_off
    tower_fan:
      friendly_name: "Tower Fan"
      command_on: !secret remote_control_code_tower_fan_on
      command_off: !secret remote_control_code_tower_fan_off

