# - platform: orvibo # <------ works, but without name
- platform: orvibo
  discovery: false
  switches:
    - host: 192.168.1.208
      mac:  !secret orvibo_wifi_socket_mac
      name: "orvibo-s20"
- platform: xiaomi_miio
  name: "Xiaomi Mi WiFi Socket Basic"
  host: 192.168.31.205
  token: !secret xiaomi_wifi_socket_basic_token