. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh
sleep 5
. /home/pi/check-hass-restart-flag.sh
. /home/pi/check-hass-openvpn-restart-flag.sh

